services:
  vllm:
    build:
      context: .
      dockerfile: vllm/Dockerfile
    ipc: host
    volumes:
      - "${LOCAL_MODEL_WEIGHTS}:/model"
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICE_ID}']
              capabilities: [gpu]
    command: [
      "--model", "/model",
      "--served-model-name", "google/medgemma-4b-it",
      "--port", "${VLLM_PORT}"
    ]
